os:
    - osx
language: swift
xcode_project: ImageUtility.xcodeproj # path to your xcodeproj folder
xcode_scheme: ImageUtilityTests
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
